sudo: false
language: node_js
node_js:
- lts/*
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
- npm run tslint
- node scripts/genAiKey.js
- npm install -g vsce
script:
- vsce package
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
